{
  imports = [
    ./arr
    ./monitoring
    ./adguardhome.nix
    ./backups.nix
    ./caddy.nix
    ./calibre-web.nix
    ./deluge.nix
    ./filebrowser.nix
    ./glances.nix
    ./homepage.nix
    ./immich.nix
    ./jellyfin.nix
    ./jellyseerr.nix
    ./miniflux.nix
    ./navidrome.nix
    ./qbittorrent.nix
    ./soulseek.nix
    ./stirling-pdf.nix
    ./tailscale.nix
    ./uptime-kuma.nix
  ];
}
