{
  imports = [
    ./arr
    ./adguardhome.nix
    ./backups.nix
    ./caddy.nix
    ./deluge.nix
    ./filebrowser.nix
    ./glances.nix
    ./homepage.nix
    ./immich.nix
    ./jellyfin.nix
    ./jellyseerr.nix
    ./linkwarden.nix
    ./netdata.nix
    ./qbittorrent.nix
    ./stirling-pdf.nix
    ./tailscale.nix
    ./uptime-kuma.nix
  ];
}
